import { configureStore } from "@reduxjs/toolkit";
import { apiSlice } from "./slices/apiSlice";
import cartSliceReducer from "./slices/cartSlice";
import authSliceReducer from "./slices/authSlice";

// This file is configuring a Redux store using Redux Toolkit’s configureStore func. This store acts as the central place to manage the state of your application.

// Create Redux store using Redux Toolkit's configureStore func.
// apiSlice is an RTK Query API slice, which manages all API-related state (like data, loading, and error status for API calls).
// apiSlice.reducerPath is a string (usually "api") that determines where in the Redux state tree the API slice’s data will be stored.
// apiSlice.reducer is the reducer function generated by RTK Query to handle all API-related actions and state updates.
// The [apiSlice.reducerPath]: apiSlice.reducer syntax uses a computed property name, ensuring the API slice’s state is stored under a specific key in the Redux state tree.
// Results: This line dynamically adds a key (like "api") to your Redux state, and the value is managed by RTK Query’s reducer.

// cart is the key in your Redux state tree for the cart’s data.
// cartSliceReducer is the reducer function from your cart slice, which manages cart items, prices, and related logic.
// Result: The cart’s state (like cart.cartItems, cart.totalPrice, etc.) is managed by this reducer.

/*
What does the Redux state look like?
  {
  api: { ... },   // Managed by RTK Query (apiSlice)
  cart: { ... }   // Managed by your cartSliceReducer
  }
*/

/* 
why the property is named 'reducer' ?
  In Redux, a reducer is a function that takes the current state and an action, and returns the new state.
  This naming follows the core Redux concept of using reducers to "reduce" / "combine" actions and state into a new state.

In Redux:
  A reducer takes two arguments: the current state and an action.
  It returns a new state based on the action type and payload.
  Reducers are pure functions: they do not modify the original state, but return a new one.

Summary:
  They are called reducers because they "reduce" (combine) state and actions into a new state, following the reducer pattern from functional programming.
*/
const store = configureStore({
  reducer: {
    [apiSlice.reducerPath]: apiSlice.reducer,
    cart: cartSliceReducer, // cartSliceReducer manages cart state
    auth: authSliceReducer, // authSliceReducer manages authentication state
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(apiSlice.middleware),
  devTools: true, // process.env.Node_ENV !== 'production'
});

/* 
What is middleware?
  Middleware in Redux intercepts actions before they reach the reducers. 
  It’s used for things like logging, handling async actions, or modifying actions.

getDefaultMiddleware():
This is a Redux Toolkit helper that returns an array of recommended middleware, including:
  redux-thunk (for async logic)
  Middleware for checking if actions and state are serializable
  Middleware for catching common mistakes

.concat(apiSlice.middleware):
This adds the middleware generated by RTK Query’s apiSlice.

  apiSlice.middleware is required for RTK Query to manage caching, data fetching, polling, and automatic updates for your API endpoints.
  By concatenating it, you ensure both the default middleware and RTK Query’s middleware are active in your store.

Summary:
  This line sets up your store to use both Redux Toolkit’s default middleware and the special middleware needed for RTK Query’s advanced features.

In short:
  RTK Query’s middleware is specialized for API data management.
  Default middleware helps with async logic, state safety, and debugging in Redux.

Are those middleware files concat with this .concat(apiSlice.middleware) line of code?
  No, those middleware files (authMiddlerware.js, errorMiddleware.js, asyncHandler.js) in your backend are not related to the .concat(apiSlice.middleware) line in your frontend Redux store.
*/

export default store;
